CREATE DATABASE COMPANY04;

USE COMPANY04;

CREATE TABLE CUSTOMERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    AGE INT,
    ADDRESS VARCHAR(255),
    SALARY DECIMAL(10, 2),
    MESSAGE VARCHAR(255) DEFAULT NULL
);

-- INSERT TRIGGER
DELIMITER //

CREATE TRIGGER after_insert_salary_difference
AFTER INSERT ON CUSTOMERS
FOR EACH ROW
BEGIN
	SET @my_sal_diff = CONCAT('salary inserted is ', NEW.SALARY);
END;//

DELIMITER ;

-- UPDATE TRIGGER
DELIMITER //

CREATE TRIGGER after_update_salary_difference
AFTER UPDATE ON CUSTOMERS
FOR EACH ROW
BEGIN
    DECLARE old_salary DECIMAL(10, 2);
    DECLARE new_salary DECIMAL(10, 2);
    
    SET old_salary = OLD.SALARY;
    SET new_salary = NEW.SALARY;
	SET @my_sal_diff = CONCAT('salary difference after update is ', NEW.SALARY - OLD.SALARY);
END;//

DELIMITER ;

-- DELETE TRIGGER
DELIMITER //

CREATE TRIGGER after_delete_salary_difference
AFTER DELETE ON CUSTOMERS
FOR EACH ROW
BEGIN
	SET @my_sal_diff = CONCAT('salary deleted is ', OLD.SALARY);
END;//

DELIMITER ;

-- test INSERT TRIGGER
INSERT INTO CUSTOMERS (NAME, AGE, ADDRESS, SALARY)
VALUES ('Shankara', 35, '123 Main St', 50000.00);

SELECT @my_sal_diff AS SAL_DIFF;

-- test UPDATE TRIGGER
UPDATE CUSTOMERS
SET SALARY = 55000.00
WHERE ID = 1;

SELECT @my_sal_diff AS SAL_DIFF;

-- test DELETE TRIGGER
DELETE FROM CUSTOMERS
WHERE ID = 1;

SELECT @my_sal_diff AS SAL_DIFF;


